<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="keywords" content=""/>
  <meta name="description" content=""/>
  <title>@@pagetitle</title>
  <link rel="icon" href="@@webroot/assets/ico/favicon.ico">
  <link rel="canonical" href="javascript:;">

  <!-- COMM -->
  <link rel="stylesheet" href="https://www.hyundai.com/etc/designs/hyundai/in/en/dependencies.css" type="text/css">
  <link rel="stylesheet" href="https://www.hyundai.com/etc/designs/hyundai/in/en/global.css" type="text/css">
  <link rel="stylesheet" href="https://www.hyundai.com/etc/designs/hyundai/in/en/components/common/header.css" type="text/css">
  <link rel="stylesheet" href="https://www.hyundai.com/etc/designs/hyundai/in/en/components/pip/text-headline.css" type="text/css">

  <!-- <script type="text/javascript" src="https://www.hyundai.com/etc/designs/hyundai/in/en/dependencies.js"></script> -->
  <!-- <script type="text/javascript" src="https://www.hyundai.com/etc/designs/hyundai/in/en/components/common/header.js"></script> -->
  <!--// COMM -->

  <link rel="stylesheet" href="@@webroot/assets/css/ui.css" />
  <script type="text/javascript" src="@@webroot/assets/js/jquery-1.11.3.min.js"></script>
  <script type="text/javascript" src="@@webroot/assets/js/ui-plugin.js"></script>

